import streamlit as st
from PIL import Image
import torch
import torchvision.transforms as transforms
from torchvision.models import resnet152
import torch.nn as nn
import torch.nn.functional as F

# Define the captioning model
class ImageCaptioningModel(nn.Module):
    def __init__(self, embed_size, hidden_size, vocab_size, num_layers):
        super(ImageCaptioningModel, self).__init__()
        self.resnet = resnet152(pretrained=True)
        self.resnet.fc = nn.Linear(self.resnet.fc.in_features, embed_size)
        self.embed = nn.Embedding(vocab_size, embed_size)
        self.lstm = nn.LSTM(embed_size, hidden_size, num_layers, batch_first=True)
        self.linear = nn.Linear(hidden_size, vocab_size)

    def forward(self, images, captions):
        features = self.resnet(images)
        embeddings = self.embed(captions)
        embeddings = torch.cat((features.unsqueeze(1), embeddings), 1)
        lstm_out, _ = self.lstm(embeddings)
        outputs = self.linear(lstm_out)
        return outputs

# Load pre-trained model and vocabulary
vocab_size = 10000  # Example vocabulary size
embed_size = 256  # Example embedding size
hidden_size = 512  # Example hidden size
num_layers = 1  # Example number of layers

model = ImageCaptioningModel(embed_size, hidden_size, vocab_size, num_layers)
# Load pre-trained weights
model.load_state_dict(torch.load("your_model_weights.pth", map_location=torch.device('cpu')))
model.eval()

# Define transformations for images
transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
])

# Function to generate caption for uploaded image
def generate_caption(image):
    image = transform(image).unsqueeze(0)
    caption = "Caption will be generated here"  # Placeholder
    # Use your model to generate caption here
    # Example:
    # output = model(image, captions)
    # caption = process_output(output)
    return caption

# Streamlit app
st.title("Image Caption Generator")
st.write("Upload an image and get a caption generated by AI.")

uploaded_file = st.file_uploader("Choose an image...", type=["jpg", "jpeg", "png"])

if uploaded_file is not None:
    image = Image.open(uploaded_file)
    st.image(image, caption='Uploaded Image', use_column_width=True)
    caption = generate_caption(image)
    st.write("Generated Caption:")
    st.write(caption)
